export const SET_POKEMONS_TYPE = 'SET_POKEMONS_TYPE';
export const SET_POKEMONS_LIST = 'SET_POKEMONS_LIST';
export const SET_POKEMON_INFO = 'SET_POKEMON_INFO';
export const SET_ERROR_INFO = 'SET_ERROR_INFO';
export const CHANGE_LOADING_STATUS = 'CHANGE_LOADING_STATUS';
