export const GET_POKEMON_LIST_STARTED = 'GET_POKEMON_LIST_STARTED';
export const GET_POKEMON_LIST_SUCCESS = 'GET_POKEMON_LIST_SUCCESS';
export const GET_POKEMON_LIST_ERR = 'GET_POKEMON_LIST_ERR';

export const GET_POKEMON_INFO_STARTED = 'GET_POKEMON_INFO_STARTED';
export const GET_POKEMON_INFO_SUCCESS = 'GET_POKEMON_INFO_SUCCESS';
export const GET_POKEMON_INFO_ERR = 'GET_POKEMON_INFO_ERR';

export const GET_POKEMON_TYPES_START = 'GET_POKEMON_TYPES_START';
export const GET_POKEMON_TYPES_SUCCESS = 'GET_POKEMON_TYPES_SUCCESS';
export const GET_POKEMON_TYPES_ERR = 'GET_POKEMON_TYPES_ERR';

export const SET_PAGE = 'SET_PAGE';
